#! /bin/bash

RINGMASTER_HOSTNAME="vcm-2352.vm.duke.edu"
RINGMASTER_PORT=51067
NUM_PLAYERS=20
NUM_HOPS=100
./ringmaster $RINGMASTER_PORT $NUM_PLAYERS $NUM_HOPS &

sleep 0.5

for (( i=0; i<$NUM_PLAYERS; i++ ))
do
    ./player $RINGMASTER_HOSTNAME $RINGMASTER_PORT &
done

wait
